### ISSUE TITLE
Unable to parse compound selector where ID follows class

### ISSUE THREAD

**Issue by aweary** [gajus/scalpel#6]
If I try to parse the selector:

```js
"div.foo#bar"
```

I get the following error:

```
Error: invalid syntax at line 1 col 8:

  div.foo#bar
         ^
Unexpected "#"

    at Parser.feed (/{PATH}/node_modules/nearley/lib/nearley.js:320:23)
    at Object.parse (/{PATH}/node_modules/scalpel/dist/createParser.js:24:26)
    at repl:1:3
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
```

It works fine if I reverse the ordering of the selectors, e.g., `div#bar.foo`. Both are valid and should be parsed successfully.

**Comment by aweary** [comment]
It seems like there is a specific order for all selector types. I believe it's because of [this definition for `selectorBody`](https://github.com/gajus/scalpel/blob/master/src/grammar.ne#L40). @gajus is there a way to define the grammar where the order of the selectors doesn't matter?

**Comment by gajus** [comment]
Is `div.foo#bar` even a valid selector? If nothing else, it is helluva confusing way of writing a selector.

**Comment by aweary** [comment]
I agree it's not a great practice, but as far as I can tell it's a valid selector. The CSS2 spec explicitly states selectors are unordered, and the CSS3 spec makes no mention of order. Plus, it's accepted as valid by all the browsers I tried.

**Comment by aweary** [comment]
@gajus I'm happy to work on this but I'm not super familiar with writing grammars. Do you know how I would express this unambiguously? Specifically how to tell the parser that it could be any of those selector types in any order (with the exception of type selectors coming first if they exist). 

The spec defines simple selector sequences as:

```
simple_selector_sequence
  : [ type_selector | universal ]
    [ HASH | class | attrib | pseudo | negation ]*
  | [ HASH | class | attrib | pseudo | negation ]+
  ;
```

**Comment by gajus** [comment]
> Do you know how I would express this unambiguously?

I haven't touched this for over 7 months. Making the change would equally require me to do the research.
